services:

    # Manager
    idci_code_generator.manager:
        class: IDCI\Bundle\CodeGeneratorBundle\CodeGeneratorManager
        arguments:
            - @idci_code_generator.generator_registry
            - @idci_code_generator.validator_registry
            - @idci_code_generator.configurator_builder


    # Configurator
    idci_code_generator.configurator_builder:
        class: IDCI\Bundle\CodeGeneratorBundle\Configuration\CodeGeneratorConfiguratorBuilder
        arguments: [%idci_code_generator.charsets%]


    # Generator
    idci_code_generator.generator_registry:
        class: IDCI\Bundle\CodeGeneratorBundle\Generation\CodeGeneratorRegistry

    idci_code_generator.generator.mt_rand:
        class: IDCI\Bundle\CodeGeneratorBundle\Generation\MtRandCodeGenerator
        tags:
            - { name: code_generator, alias: mtrand }


    # Validator
    idci_code_generator.validator_registry:
        class: IDCI\Bundle\CodeGeneratorBundle\Validation\CodeValidatorRegistry

    idci_code_generator.validator.array:
        class: IDCI\Bundle\CodeGeneratorBundle\Validation\ArrayCodeValidator
        tags:
            - { name: code_validator, alias: array }