services:

    # Manager
    idci_code_generator.manager:
        class: IDCI\Bundle\CodeGeneratorBundle\CodeGeneratorManager
        arguments:
            - @idci_code_generator.configurator_builder
            - @idci_code_generator.generator_registry
            - @idci_code_generator.validator_registry


    # Configurator
    idci_code_generator.configurator_builder:
        class: IDCI\Bundle\CodeGeneratorBundle\Configuration\CodeGeneratorConfiguratorBuilder
        arguments: [%idci_code_generator.charsets%]


    # Generator
    idci_code_generator.generator_registry:
        class: IDCI\Bundle\CodeGeneratorBundle\Generation\CodeGeneratorRegistry

    idci_code_generator.generator.random:
        class: IDCI\Bundle\CodeGeneratorBundle\Generation\RandomCodeGenerator
        tags:
            - { name: code_generator, alias: random }


    # Validator
    idci_code_generator.validator_registry:
        class: IDCI\Bundle\CodeGeneratorBundle\Validation\CodeValidatorRegistry


    # Form
    form.type.code_generation_configuration:
        class: IDCI\Bundle\CodeGeneratorBundle\Form\Type\GenerationConfigurationType
        arguments: [%idci_code_generator.charsets%]
        tags:
            - { name: form.type, alias: code_generation_configuration }

    form.type.code_generator_configuration:
        class: IDCI\Bundle\CodeGeneratorBundle\Form\Type\CodeGeneratorConfigurationType
        tags:
            - { name: form.type, alias: code_generator_configuration }